relativeURLs = true
title = "Liam Frölund"
theme = ["academimal"]
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml" , "make.sh"]

[params]
    shortbio = "Agricultural and Resource Economics Ph.D. student at UC Berkeley"
    logo = "images/lfrolund_portrait.jpg" 
    author = "Liam Frölund"
    sitename = "Personal website of Liam Frölund"
    
  